### ISSUE TITLE
Add SimpleDate to METADATA.jl

### ISSUE THREAD

**Issue by pygy** [aviks/SimpleDate.jl#1]
It would be great if you could send a pull request to [METADATA.jl](https://github.com/JuliaLang/METADATA.jl#recipe-for-packaging-an-existing-repository).

I'm writing a TOML parser, and would like to rely on it.

Thanks for your work!

**Comment by aviks** [comment]
Hi, have you looked at Calendar.jl package? That package uses ICU, and currently has more functionality than this one. Will that suffice for your needs now? Or do you need native Julia date algorithm?

I do plan to put in the additional functionality into this at some point. So happy to add this to metadata if you need it.

**Comment by pygy** [comment]
Thanks, it should do it, thanks. I searched for date in the package list, not time...

**Comment by pygy** [comment]
Going through my issues backlog, closing old stuff...
